### ISSUE TITLE
Not compiled swift 3.0

### ISSUE THREAD

**Issue by dgalluccio** [frograin/SuperSimpleMapper#1]
Hi @frograin this class does not compile with swift 3 and I have a compatibility problem with ObjectMapper

**Comment by frograin** [comment]
The library is now swift 3. It's been packaged as pod so you should not have any problem with other libraries. 
Note that at the present time, the pod is not published on the public repo so you'll need to install it as development pod if you want to use it in your project. Use the Example app provided as reference.
